name: Andrew Carringer
markdown: kramdown

# Social Media
twitter_username: mitipodesalsa
facebook_username: andrew.carringer
instagram_username: rackinfracknvarmit
github_username:  andrewcarringer

permalink: /Blog/:year/:month/:day/:title
